services:
  mysql-db:
    image: mysql:8.0
    container_name: catalogo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: huertohogar_catalog
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  catalogo-app:
    build: .
    container_name: catalogo-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/huertohogar_catalog?useSSL=false&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      JWT_SECRET: SDu+O89zOOVF6HnYsPnmhtkWNpE3U3ZG6Q2u4rwsf9c=
      JWT_EXPIRATION: 3600000
    depends_on:
      mysql-db:
        condition: service_healthy
      
