apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogo-config
  namespace: catalogo
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/huertohogar_catalog?useSSL=false&serverTimezone=America/Santiago"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  SERVER_PORT: "8082"
